import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'

import SideNav from './components/navigation/sideNav'
import TopNav from './components/navigation/TopNav'
import { allData } from './components/background/utils/allData'
import BackgroundCard from './components/background/BackgroundCard'

import './globals.css'


const inter = Inter(
  { subsets: ['latin'] }
  )

export const metadata: Metadata = {
  title: 'Gamemano',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <html lang="en">
      <body className={inter.className}>

      <NextTopLoader
          color="#DAB785"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        
        <SideNav />
        <TopNav />
        
        {children}
        <BackgroundCard {...allData['2']} />
        <div className='gapDiv'></div>
        <BackgroundCard {...allData['3']} />
        <div className='gapDiv'></div>
        <BackgroundCard {...allData['4']} />
        <div className='gapDiv'></div>
        
      </body>
    </html>
  )
}
